/**
 * Headless checks for the pure logic: formatting, filenames, grouping and the
 * PDF byte layout. The extraction path needs a live YouTube tab and is covered
 * by the manual checklist in the README instead.
 *
 * Run: node scripts/selftest.mjs
 */

import { build } from 'esbuild';
import fs from 'fs';
import path from 'path';
import os from 'os';
import { fileURLToPath, pathToFileURL } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.resolve(__dirname, '..');

const entry = path.join(os.tmpdir(), `ytx-selftest-${process.pid}.mjs`);
fs.writeFileSync(
  entry,
  [
    `export * from ${JSON.stringify(path.join(rootDir, 'src', 'formatters.ts').replace(/\\/g, '/'))};`,
    `export * from ${JSON.stringify(path.join(rootDir, 'src', 'pdf.ts').replace(/\\/g, '/'))};`,
    `export * from ${JSON.stringify(path.join(rootDir, 'src', 'transcript-extractor.ts').replace(/\\/g, '/'))};`,
    `export * from ${JSON.stringify(path.join(rootDir, 'src', 'cleanup.ts').replace(/\\/g, '/'))};`,
    `export { describeActions } from ${JSON.stringify(path.join(rootDir, 'src', 'history.ts').replace(/\\/g, '/'))};`,
  ].join('\n')
);

const bundlePath = path.join(os.tmpdir(), `ytx-selftest-bundle-${process.pid}.mjs`);
await build({
  entryPoints: [entry],
  bundle: true,
  format: 'esm',
  platform: 'node',
  target: ['node20'],
  outfile: bundlePath,
  logLevel: 'silent',
});

const mod = await import(pathToFileURL(bundlePath).href);

let failures = 0;
function check(name, condition, detail) {
  if (condition) {
    console.log(`  ok   ${name}`);
  } else {
    failures++;
    console.log(`  FAIL ${name}${detail ? ` — ${detail}` : ''}`);
  }
}

/* ── Fixtures ────────────────────────────────────────────────────────── */

const segments = [];
for (let i = 0; i < 400; i++) {
  segments.push({ text: `Caption line number ${i} with some words in it.`, start: i * 5, duration: 5 });
}

const result = {
  segments,
  languageKey: 'track:0',
  languageName: 'English',
  isAutoGenerated: false,
  availableLanguages: [],
  meta: {
    videoId: 'dQw4w9WgXcQ',
    title: 'How to build things: a "practical" guide / part 1',
    channel: 'Some Channel',
    durationSeconds: 3725,
    url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
  },
};

// Cleanup and chapters default off in the fixtures so the older checks below
// keep testing exactly what they were written to test.
const base = { cleanCaptions: false, linkTimestamps: false, useChapters: false };
const withTimestamps = { includeTimestamps: true, includeHeader: true, paragraphMode: 'paragraphs', ...base };
const bare = { includeTimestamps: false, includeHeader: false, paragraphMode: 'lines', ...base };

/* ── Timestamps ──────────────────────────────────────────────────────── */

console.log('timestamps');
check('mm:ss under an hour', mod.formatTimestamp(75) === '01:15', mod.formatTimestamp(75));
check('hh:mm:ss over an hour', mod.formatTimestamp(3725) === '01:02:05', mod.formatTimestamp(3725));
check('forced hours', mod.formatTimestamp(75, true) === '00:01:15', mod.formatTimestamp(75, true));

/* ── Grouping ────────────────────────────────────────────────────────── */

console.log('grouping');
const grouped = mod.groupSegments(segments);
check('merges lines into blocks', grouped.length > 0 && grouped.length < segments.length, `${grouped.length} blocks`);
check('first block starts at zero', grouped[0].start === 0);
check('blocks stay under the char cap', grouped.every(g => g.text.length < 600));
check('no text lost', grouped.map(g => g.text).join(' ').split(' ').length === segments.map(s => s.text).join(' ').split(' ').length);

/* ── Markdown / text ─────────────────────────────────────────────────── */

console.log('markdown & text');
const md = mod.toMarkdown(result, withTimestamps);
check('markdown has a title heading', md.startsWith(`# ${result.meta.title}`));
check('markdown carries the header block', md.includes('**Channel:** Some Channel') && md.includes('**Duration:** 01:02:05'));
check('markdown timestamps use hours', /\*\*\[00:00:00\]\*\*/.test(md));

const bareMd = mod.toMarkdown(result, bare);
check('header can be turned off', !bareMd.includes('**Channel:**') && !bareMd.startsWith('#'));
check('timestamps can be turned off', !/\[\d\d:\d\d/.test(bareMd));
check('line mode keeps every caption', bareMd.trim().split('\n\n').length === segments.length);

const txt = mod.toPlainText(result, withTimestamps);
check('text export has no markdown syntax', !txt.includes('**'));
check('text export includes the url', txt.includes(result.meta.url));

/* ── Filenames ───────────────────────────────────────────────────────── */

console.log('filenames');
const filename = mod.buildFilename(result, 'md');
check('follows the convention', filename === 'Some Channel - How to build things a practical guide part 1 - transcript.md', filename);
check('drops filesystem-hostile characters', !/[\\/:*?"<>|]/.test(filename));

const longResult = {
  ...result,
  meta: { ...result.meta, title: 'x'.repeat(400), channel: 'y'.repeat(80) },
};
const longName = mod.buildFilename(longResult, 'pdf');
check('truncates to 120 characters', longName.length <= 120, `${longName.length} chars`);
check('keeps the extension after truncation', longName.endsWith(' - transcript.pdf'));

/* ── PDF ─────────────────────────────────────────────────────────────── */

console.log('pdf');
const pdf = mod.generatePdf(mod.toPdfDocument(result, withTimestamps));
const bytes = new Uint8Array(await pdf.blob.arrayBuffer());
const text = Buffer.from(bytes).toString('latin1');

check('has a PDF header', text.startsWith('%PDF-1.4'));
check('ends with EOF', text.trimEnd().endsWith('%%EOF'));
check('reports no unsupported characters for ASCII', pdf.unsupportedCharacters.length === 0, pdf.unsupportedCharacters.join(''));
check('paginates a long transcript', (text.match(/\/Type \/Page[^s]/g) || []).length > 1, `${(text.match(/\/Type \/Page[^s]/g) || []).length} pages`);

// The real risk in a hand-rolled PDF is the cross-reference table, so verify
// every offset actually lands on its object header.
const startxref = Number(text.match(/startxref\s+(\d+)/)[1]);
check('startxref points at the xref table', text.slice(startxref, startxref + 4) === 'xref');

const xrefBody = text.slice(startxref);
const entries = [...xrefBody.matchAll(/^(\d{10}) (\d{5}) ([nf])/gm)];
let offsetsOk = true;
entries.forEach(([, offset, , type], index) => {
  if (type === 'f') return;
  const at = Number(offset);
  if (!text.slice(at).startsWith(`${index} 0 obj`)) offsetsOk = false;
});
check('every xref offset lands on its object', offsetsOk);
check('xref size matches the object count', entries.length === Number(text.match(/\/Size (\d+)/)[1]));

const cyrillic = mod.generatePdf({ title: 'Привет мир', header: [], lines: [{ label: '', text: 'Привет' }] });
check('flags characters a standard PDF font cannot draw', cyrillic.unsupportedCharacters.length > 0);

/* ── Caption cleanup ─────────────────────────────────────────────────── */

console.log('\ncleanup');
check(
  'turns a mid-line speaker marker into a break',
  mod.cleanLine('yes I agree >> well I do not') === 'Yes I agree — well I do not',
  mod.cleanLine('yes I agree >> well I do not')
);
check(
  'drops a speaker marker that opens the line',
  mod.cleanLine('>> I see what you mean') === 'I see what you mean',
  mod.cleanLine('>> I see what you mean')
);
check('capitalises the first word', mod.cleanLine('hello there') === 'Hello there');
check(
  'capitalises after a full stop',
  mod.cleanLine('one thing. another thing') === 'One thing. Another thing'
);
check('raises a standalone i', mod.cleanLine('so i said') === 'So I said');
check('leaves i inside a word alone', mod.cleanLine('it is inside') === 'It is inside');
check('collapses runaway spacing', mod.cleanLine('too   many    spaces') === 'Too many spaces');
check(
  'does not invent punctuation',
  mod.cleanLine('no full stop here') === 'No full stop here'
);
check(
  'keeps sound cues unless asked',
  mod.cleanLine('[Music] and then') === '[Music] and then',
  mod.cleanLine('[Music] and then')
);
check(
  'drops sound cues when asked',
  mod.cleanLine('[Music] and then', { dropSoundCues: true }) === 'And then'
);
check(
  'a line of nothing but a cue collapses to empty',
  mod.cleanSegments([{ text: '[Applause]', start: 0, duration: 1 }], { dropSoundCues: true }).length === 0
);

// The bug this split exists to prevent: casing applied per caption fragment
// capitalises every fragment boundary, which lands mid-sentence once the
// fragments are merged — "what will Work for me".
check(
  'phase one leaves casing alone',
  mod.cleanFragment('what will work for me') === 'what will work for me'
);
check(
  'phase two capitalises only real sentence starts',
  mod.finishText('what will work for me. and so there is') ===
    'What will work for me. And so there is'
);
const merged = mod.toMarkdown(
  {
    ...result,
    segments: [
      { text: 'trying to figure out', start: 0, duration: 2 },
      { text: 'what will work for me', start: 2, duration: 2 },
      { text: 'and so there is a movie about guys', start: 4, duration: 2 },
    ],
  },
  { includeTimestamps: false, includeHeader: false, paragraphMode: 'paragraphs', cleanCaptions: true, linkTimestamps: false, useChapters: false }
);
check(
  'a merged paragraph is not capitalised at every fragment',
  !/ Work | Guys | And so/.test(merged),
  merged.trim()
);

/* ── Links, chapters and the prompt ──────────────────────────────────── */

console.log('\nlinks & chapters');
const linked = mod.toMarkdown(result, { ...withTimestamps, linkTimestamps: true });
check('markdown timestamps become links', linked.includes('](https://www.youtube.com/watch?v=dQw4w9WgXcQ&t='), linked.slice(200, 320));
check(
  'the link points at the second the line starts',
  linked.includes('[00:00:00](https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=0)')
);
check('plain text keeps timestamps plain', !mod.toPlainText(result, withTimestamps).includes('](http'));

const chaptered = { ...result, chapters: [{ title: 'The setup', start: 0 }, { title: 'The point', start: 600 }] };
const chapterMd = mod.toMarkdown(chaptered, { ...withTimestamps, useChapters: true });
check('chapters become headings', chapterMd.includes('## The setup') && chapterMd.includes('## The point'));
check('a heading appears once', (chapterMd.match(/## The point/g) || []).length === 1);
check(
  'chapters can be turned off',
  !mod.toMarkdown(chaptered, { ...withTimestamps, useChapters: false }).includes('## The setup')
);
check(
  'the pdf gets the chapter as its own line',
  mod.toPdfDocument(chaptered, { ...withTimestamps, useChapters: true }).lines.some(l => l.text === 'THE SETUP')
);

console.log('\nprompt');
const instruction = 'Below is the transcript of a YouTube video. Summarise it.';
const prompt = mod.toPrompt(result, withTimestamps, instruction);
check('leads with the instruction, not the transcript', prompt.startsWith(instruction));
check(
  'a custom instruction replaces the built-in one',
  mod.toPrompt(result, withTimestamps, 'Translate this to French.').startsWith('Translate this to French.')
);
check('names the video and channel', prompt.includes(result.meta.title) && prompt.includes('Some Channel'));
check('carries the transcript body', prompt.includes('Caption line number 0'));
check('keeps timestamps for citing', /\[00:00:00\]/.test(prompt));

/* ── Notes as PDF ────────────────────────────────────────────────────── */

console.log('\nnotes pdf');
{
  const doc = mod.notesToPdfDocument(
    'A video',
    [
      '# A video',
      '',
      '**Channel:** Someone',
      '',
      '---',
      '',
      '## The setup',
      '',
      '**[[00:12](https://youtu.be/x&t=12)]** He says the thing.',
      '',
      '> A quote worth keeping',
      '',
      '- a bullet with **bold** in it',
      '1. a numbered point',
      '',
      'Plain prose with a [link](https://example.com) in it.',
    ].join('\n')
  );
  const texts = doc.lines.map(l => l.text);

  check('a heading becomes its own line', texts.includes('THE SETUP'));
  check(
    'a seeded transcript line keeps its timestamp as the label',
    doc.lines.some(l => l.label === '[00:12]' && l.text === 'He says the thing.'),
    JSON.stringify(doc.lines.find(l => l.label === '[00:12]'))
  );
  check('a bullet keeps its marker and loses its asterisks', texts.includes('• a bullet with bold in it'));
  check('a numbered point keeps its number as the label', doc.lines.some(l => l.label === '1.'));
  check('a quote is quoted', texts.some(t => t.startsWith('“') && t.includes('worth keeping')));
  check('a link keeps its words, not its url', texts.some(t => t === 'Plain prose with a link in it.'));
  check('the horizontal rule is dropped', !texts.includes('---'));
  check('no markdown punctuation survives', !texts.some(t => /\*\*|\]\(/.test(t)), texts.join(' | '));

  // The writer has to accept what this produces, not merely look right.
  const notesPdf = mod.generatePdf(doc);
  check('the notes pdf is a pdf', notesPdf.blob.size > 400);
}

/* ── History labels ──────────────────────────────────────────────────── */

console.log('\nhistory');
check('one action reads plainly', mod.describeActions(['copy']) === 'Copied');
check(
  'several actions are joined in the order taken',
  mod.describeActions(['copy', 'md', 'pdf']) === 'Copied · .md · .pdf',
  mod.describeActions(['copy', 'md', 'pdf'])
);
check('no actions says nothing', mod.describeActions([]) === '');

const outPdf = path.join(rootDir, 'dist', 'selftest-sample.pdf');
if (fs.existsSync(path.dirname(outPdf))) {
  fs.writeFileSync(outPdf, bytes);
  console.log(`\nSample PDF written to ${path.relative(process.cwd(), outPdf)} — open it to eyeball the layout.`);
}

fs.rmSync(entry, { force: true });
fs.rmSync(bundlePath, { force: true });

console.log(failures ? `\n${failures} check(s) failed.` : '\nAll checks passed.');
process.exit(failures ? 1 : 0);
