export interface TranscriptSegment {
  text: string;
  /** Seconds from the start of the video. */
  start: number;
  duration: number;
}

export interface AvailableLanguage {
  code: string;
  name: string;
  /** True when the track is an auto-translation rather than a real caption track. */
  isTranslation: boolean;
  isAutoGenerated: boolean;
  /** Stable key used by the language <select> — codes alone are not unique (manual + ASR). */
  key: string;
}

export interface VideoMeta {
  videoId: string;
  title: string;
  channel: string;
  /** Seconds; 0 when YouTube did not report a length. */
  durationSeconds: number;
  url: string;
}

export interface TranscriptResult {
  segments: TranscriptSegment[];
  /** The video's own chapters, empty when it has none. */
  chapters?: Chapter[];
  languageKey: string;
  languageName: string;
  isAutoGenerated: boolean;
  availableLanguages: AvailableLanguage[];
  meta: VideoMeta;
}

/**
 * Reason buckets for the local failure counter. Kept coarse on purpose — these
 * are the only failure labels that ever get counted, and none of them carry
 * video-identifying data.
 */
export type FailureReason =
  | 'not-youtube'
  | 'no-video'
  | 'no-captions'
  | 'live'
  | 'unavailable'
  | 'pot-failed'
  | 'network'
  | 'parse'
  | 'unknown';

export class TranscriptError extends Error {
  constructor(public readonly reason: FailureReason, message: string) {
    super(message);
    this.name = 'TranscriptError';
  }
}

export interface ExportOptions {
  includeTimestamps: boolean;
  includeHeader: boolean;
  /** 'lines' = raw caption lines, 'paragraphs' = merged into ~60s blocks. */
  paragraphMode: 'lines' | 'paragraphs';
  /** Tidy the captions: speaker markers, sentence casing. See src/cleanup.ts. */
  cleanCaptions: boolean;
  /** Markdown only: turn each timestamp into a link back to that moment. */
  linkTimestamps: boolean;
  /** Use the video's own chapters as headings, where it has any. */
  useChapters: boolean;
}

/** A chapter from the video's own chapter list. */
export interface Chapter {
  title: string;
  /** Seconds from the start of the video. */
  start: number;
}

export const DEFAULT_EXPORT_OPTIONS: ExportOptions = {
  includeTimestamps: true,
  includeHeader: true,
  paragraphMode: 'paragraphs',
  cleanCaptions: true,
  linkTimestamps: true,
  useChapters: true,
};

/* ── Messages ────────────────────────────────────────────────────────── */

export interface FetchUrlMessage {
  type: 'YTX_FETCH_URL';
  url: string;
}

export interface FetchUrlResponse {
  ok: boolean;
  status?: number;
  body?: string;
  error?: string;
}

export interface OpenPanelMessage {
  type: 'YTX_OPEN_PANEL';
}

export interface NavigatedMessage {
  type: 'YTX_NAVIGATED';
  url: string;
}

/** Play position, pushed by the content script while the panel is following. */
export interface TimeMessage {
  type: 'YTX_TIME';
  seconds: number;
}

/** Turns that reporting on and off — nobody should be timing a closed panel. */
export interface TrackMessage {
  type: 'YTX_TRACK';
  on: boolean;
}
